name: Build

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build Unix
        if: matrix.os != 'windows-latest'
        run: make build
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: go build -x -v -o gia cmd/main.go
