name: Test application

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Test
        run: make test
  MacOs:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Test
        run: make test
  Windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Test
        run: go test -v
